// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibqhlkiqfsvsvgjrouzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlicWhsa2lxZnN2c3ZnanJvdXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjI2NjIsImV4cCI6MjA2ODk5ODY2Mn0.BKPj7C35Lx4Y78KqkqT9NKIvd1Uo6h3sC79gL5gCSAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});